import styles from "@/styles/About.module.css"
import Head from "next/head"
import Link from "next/link"

export const getStaticProps = async () => {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_STUDIOASA}kategori-project?per_page=100`
  )

  const data = await res.json()

  return {
    props: { projects: data },
  }
}

const About = ({ projects }: { projects: any }) => {
  const services = [
    {
      image: "/Homepage/projectimage.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageArchitecture.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimage.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageCommercial.jpeg",
      title: "Commerce",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimage.jpeg",
      title: "Commerce",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageGardenDesign.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageInteriorDesign.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimage.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageI.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageOffice.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageResidential.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
    {
      image: "/Homepage/projectimageRetail.jpeg",
      title: "Garden Design",
      project: "15",
      city: "15",
    },
  ]

  return (
    <>
      <Head>
        <title>About Us - Studio Asa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo Studio Asa.svg" />
      </Head>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.belief}>
        <div className={styles.container}>
          <div className={styles.row1}>
            <div className={styles.beliefHeading}>
              <div className={styles.lineAlt}></div>
              <h1>Our Belief</h1>
            </div>
            <div className={styles.line}></div>
            <div className={styles.paragraph1}>
              <p>
                <b>Studio ASA</b> is a dynamic architecture, interior design,
                and landscape design studio based on the belief that harmonious
                living spaces must integrate nature and the built environment.
                Founded in 2019 by architect Amelinda Vidyasti and interior
                designer Bey Riffandie, Studio ASA&apos;s design philosophy is
                based on the concept of Biophilic Design, which highlights the
                relationship between humans, space, and nature. This means that
                we incorporate natural elements, such as greenery and natural
                lighting, into our designs to create spaces that promote
                well-being and sustainability.
              </p>
            </div>
            <div className={styles.paragraph1Alt}>
              <p>
                <b>Studio ASA</b> is a Bandung based design studio, focus on
                exposing the relationship between Human, Space and Nature.
              </p>
              <p>
                With a great passion for Greens, we believed Nature can be the
                major key in Spatial Design. Nature will always be the essence
                of our design for human and space
              </p>
            </div>
          </div>
          <div className={styles.row2}>
            <img src="/About/belief.jpeg" alt="belief banner"></img>
            <p>
              We believe that nature is an essential element that should be
              present in every living space. Our team understands that humans
              have an inherent connection to nature, and incorporating natural
              elements into our designs can help create a sense of calm and
              well-being in our daily lives.
            </p>
          </div>
          <div className={styles.row3}>
            <p>
              At Studio ASA, we take pride in our ability to design spaces that
              reflect our clients&apos; unique needs and preferences while
              incorporating natural elements that promote well-being. Our team
              has a keen eye for detail and a passion for creating spaces that
              are not only functional but also aesthetically pleasing. We
              believe that the integration of nature into our designs is not
              only beautiful but also has a positive impact on our well-being.
              Our goal is to create living spaces that are in harmony with
              nature and enhance the connection between humans and the natural
              world.
            </p>
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.service}>
        <div className={styles.container}>
          <div className={styles.serviceHeading}>
            <h1>Our Services</h1>
            <div className={styles.lineService}></div>
          </div>
          <div className={styles.cardContainer}>
            {projects?.map((project: any, i: any) => {
              const backgroundUrl = services[i]?.image
              if (
                project?.parent === 0 &&
                project?.name !== "Team" &&
                project?.name !== "featured"
              )
                return (
                  <Link
                    href={`/project?filter=${project.name}`}
                    className={styles.serviceCard}
                    style={{
                      background: `url(${backgroundUrl}) lightgray 50% / cover no-repeat`,
                      backgroundSize: "cover",
                    }}
                  >
                    <div className={styles.serviceTextUpper}>
                      <h1>{project.name}</h1>
                      <div className={styles.serviceCardTextLower}>
                        <h6>{project.count} project</h6>
                      </div>
                    </div>
                  </Link>
                )
              else return
            })}
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.people}>
        <div className={styles.container}>
          <div className={styles.peopleHeading}>
            <h1>People Behind</h1>
            <hr />
          </div>
          <div className={styles.profile}>
            <img
              src="/About/profile.jpeg"
              alt="profile"
              className={styles.mainProfile}
            />
            <img
              src="/About/profile2.jpeg"
              alt="profile"
              className={styles.secProfile}
            />
            <div className={styles.name}>
              <div className={styles.Bey}>
                <h2>Bey Riffandie, S.Ds.,M.B.A</h2>
                <h3>Founder - CEO</h3>
              </div>
              <div className={styles.Amelinda}>
                <h2>Amelinda Vidyasti, S.T.</h2>
                <h3>Co-Founder - Design Principal</h3>
              </div>
            </div>
          </div>
          <div className={styles.peopleParagraph}>
            <p>
              At Studio ASA, our designs are brought to life by the creative
              minds of our founders: Amelinda Vidyasti, an award-winning
              architect with a passion for landscape design, and Bey Riffandie,
              an interior designer with extensive experience in retail and
              hospitality projects. Amel, a mother of one, graduated from
              Parahyangan University and served as team leader for the
              Indonesian government&apos;s Monas Revitalization Contest. Bey
              graduated from ITB&apos;s master&apos;s program in Business
              Management and has worked in Visual Merchandising for NIKE.
            </p>
            <p>
              Together, their experience and expertise have formed the
              foundation of our studio&apos;s design philosophy that promotes
              harmony between humans, space, and nature through the adoption of
              Biophilic Design. We believe that our designs should expose the
              relationship between humans, space, and nature, and that nature
              should be the essence of our design for humans and space.
            </p>
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.client}>
        <div className={styles.container}>
          <div className={styles.clientHeading}>
            <h1>Our Client</h1>
          </div>
          <div className={styles.clientLogo}>
            <img src="/About/clients.png" alt="clients"></img>
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.contact} id="contact">
        <div className={styles.container}>
          <div className={styles.contactContent}>
            <div className={styles.contactImage}>
              <img src="/About/contact.jpeg" alt="contact" />
            </div>
            <div className={styles.contactForm}>
              <h1>Send a message</h1>
              <form>
                <input type="text" placeholder="Name" />
                <input type="text" placeholder="Email" />
                <input type="text" placeholder="Phone Number" />
                <input type="text" placeholder="Message" />
                <input type="submit" value="Send to Whatsapp" />
              </form>
            </div>
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}
    </>
  )
}

export default About
