import styles from "@/styles/PDetails.module.css"
import Image from "next/image"
import Head from "next/head"

export const getStaticPaths = async () => {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_STUDIOASA}project?per_page=100&_embed`
  )

  const data = await res.json()

  const paths = data?.map((path: any) => {
    return {
      params: { projects: path.slug },
    }
  })

  return { paths, fallback: false }
}

export const getStaticProps = async (context: any) => {
  const route = context.params.projects

  const res = await fetch(
    `${process.env.NEXT_PUBLIC_STUDIOASA}project?per_page=100&_embed`
  )

  const data = await res.json()

  /* --------------------------------------------------------------------------- */

  const contentData = data?.find((val: any) => val.slug === route)

  const filterGallery = (project: any) => {
    const galeri = project.galeri
    return galeri.split(",")
  }

  const ids: any[] = [filterGallery(contentData)]

  const results: string[][] = ids.map((latestId: string[]) => {
    return [
      `${process.env.NEXT_PUBLIC_STUDIOASA}media?include=${latestId.join(",")}`,
    ]
  })

  const fetchPromise = results.map(async (url) => {
    // Fetch each URL individually
    const response = await fetch(url[0])

    return await response.json()
  })

  const galleryFetch = await Promise.all(fetchPromise).then((dataArray) => {
    return dataArray
  })

  const galleries = galleryFetch.map((urls: any) => {
    return urls.map((url: any) => url.source_url)
  })

  const imageGalleries = galleries.map((images: any) => {
    const projectData = contentData

    return {
      ...projectData,
      images,
    }
  })

  return {
    props: { galeri: imageGalleries, content: contentData },
  }
}

const ProjectDetails = ({ galeri, content }: { galeri: any; content: any }) => {
  return (
    <>
      <Head>
        <title>details - Studio Asa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo Studio Asa.svg" />
      </Head>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.hero}>
        <img
          src={content._embedded["wp:featuredmedia"][0].source_url}
          alt="hero"
          width={1440}
          height={480}
        />
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.description}>
        <div className={styles.container}>
          <div className={styles.descriptionContent}>
            <div className={styles.contentLeft}>
              <div className={styles.title}>
                <h5>Project</h5>
                <h1
                  dangerouslySetInnerHTML={{
                    __html: content.title.rendered,
                  }}
                />
              </div>
              <hr />
              <div className={styles.detailContainer}>
                <div className={styles.detail}>
                  <h5>Location</h5>
                  <h2>{content.location}</h2>
                </div>
                <div className={styles.detail}>
                  <h5>Year</h5>
                  <h2>{content.year}</h2>
                </div>
                <div className={styles.detail}>
                  <h5>Client</h5>
                  <h2
                    dangerouslySetInnerHTML={{
                      __html: content.title.rendered,
                    }}
                  />
                </div>
                <div className={styles.detail}>
                  <h5>Category</h5>
                  <h2>Garden Design, Commercial</h2>
                </div>
              </div>
            </div>
            <div className={styles.contentRight}>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </p>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.highlight}>
        <div className={styles.container}>
          <div className={styles.highlightContainer}>
            {galeri[0].images?.map((image: any, i: any) => (
              <div key={i}>
                <img src={image} alt="1" width={636} height={711} />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.gallery}>
        <div className={styles.container}>
          <div className={styles.galleryContainer}>
            <hr />
            <h3>Gallery</h3>
            <div className={styles.pictures}>
              {galeri[0].images?.map((image: any, i: any) => (
                <img
                  src={image}
                  alt="galleries"
                  width={300}
                  height={163}
                  key={i}
                />
              ))}
            </div>
            <hr />
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}

      <div className={styles.info}>
        <div className={styles.container}>
          <div className={styles.infoContent}>
            <div className={styles.infoLeft}>
              <h3>The Process</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </p>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </p>
            </div>
            <div className={styles.infoRight}>
              <h3>Share Project</h3>
              <a href="">
                <img src="/Icons/link.svg" alt="link" />
              </a>
              <a href="facebook.com">
                <img src="/Icons/facebookproject.svg" alt="facebook" />
              </a>
              <a href="twitter.com">
                <img src="/Icons/twitterproject.svg" alt="twitter" />
              </a>
              <a href="linkedin.com">
                <img src="/Icons/linkedin.svg" alt="linkedin" />
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* --------------------------------------------------------------------------- */}
    </>
  )
}

export default ProjectDetails
