import styles from "@/styles/Career.module.css"
import Head from "next/head"

const Career = () => {
  return (
    <>
      <Head>
        <title>Career - Studio Asa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo Studio Asa.svg" />
      </Head>
      <div className={styles.container}>
        <div className={styles.left}>
          <h1>Career</h1>
        </div>
        <div className={styles.right}>
          <p>
            Lorem ipsum dolor sit amet consectetur. Aliquet amet viverra
            facilisi egestas. Vel bibendum enim quis nulla quis dictumst lacus
            magna.
          </p>
          <p>
            <u>hiring@studioasa.com</u>
          </p>
          <p>Email subject : POSITION_NAME</p>
        </div>
      </div>

      <div className={styles.containerAlt}>
        <div className={styles.top}>
          <h1>Career</h1>
        </div>
        <div className={styles.bottom}>
          <p>
            Lorem ipsum dolor sit amet consectetur. Aliquet amet viverra
            facilisi egestas. Vel bibendum enim quis nulla quis dictumst lacus
            magna.
          </p>
          <p>
            <u>hiring@studioasa.com</u>
          </p>
          <p>Email subject : POSITION_NAME</p>
        </div>
      </div>
    </>
  )
}

export default Career
